
import __ASTRO_IMAGE_IMPORT_0 from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_1 from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhtml-style-guide.md";
import __ASTRO_IMAGE_IMPORT_2 from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_3 from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhow-to-optimize-astro-for-technical+SEO.md";
import __ASTRO_IMAGE_IMPORT_4 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fdecibellion.mdx";
import __ASTRO_IMAGE_IMPORT_5 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Flisten-harder-audio.mdx";
import __ASTRO_IMAGE_IMPORT_6 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fmindthesound.mdx";
import __ASTRO_IMAGE_IMPORT_7 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fpanacousticon.mdx";
import __ASTRO_IMAGE_IMPORT_8 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fprodigal-ventures.mdx";
import __ASTRO_IMAGE_IMPORT_9 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fworld-wide-stereo-storefront.mdx";
import __ASTRO_IMAGE_IMPORT_10 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fusing-mdx.mdx";
import __ASTRO_IMAGE_IMPORT_11 from "../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md";
export default new Map([["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_0], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhtml-style-guide.md", __ASTRO_IMAGE_IMPORT_1], ["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_2], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhow-to-optimize-astro-for-technical+SEO.md", __ASTRO_IMAGE_IMPORT_3], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fdecibellion.mdx", __ASTRO_IMAGE_IMPORT_4], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Flisten-harder-audio.mdx", __ASTRO_IMAGE_IMPORT_5], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fmindthesound.mdx", __ASTRO_IMAGE_IMPORT_6], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fpanacousticon.mdx", __ASTRO_IMAGE_IMPORT_7], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fprodigal-ventures.mdx", __ASTRO_IMAGE_IMPORT_8], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fworld-wide-stereo-storefront.mdx", __ASTRO_IMAGE_IMPORT_9], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fusing-mdx.mdx", __ASTRO_IMAGE_IMPORT_10], ["../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_11]]);
		