
import __ASTRO_IMAGE_IMPORT_1lCvEI from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_1fQzLj from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhow-to-optimize-astro-for-technical+SEO.md";
import __ASTRO_IMAGE_IMPORT_1TvaEa from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhtml-style-guide.md";
import __ASTRO_IMAGE_IMPORT_Z18gmXG from "../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_Z1sIrJn from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md";
import __ASTRO_IMAGE_IMPORT_ZQqsOE from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fusing-mdx.mdx";
import __ASTRO_IMAGE_IMPORT_Zk9013 from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fdecibellion.mdx";
import __ASTRO_IMAGE_IMPORT_Z2ndESg from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Flisten-harder-audio.mdx";
import __ASTRO_IMAGE_IMPORT_iIEJQ from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fworld-wide-stereo-storefront.mdx";
export default new Map([["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_1lCvEI], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhow-to-optimize-astro-for-technical+SEO.md", __ASTRO_IMAGE_IMPORT_1fQzLj], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fhtml-style-guide.md", __ASTRO_IMAGE_IMPORT_1TvaEa], ["../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_Z18gmXG], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fmarkdown-style-guide.md", __ASTRO_IMAGE_IMPORT_Z1sIrJn], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fweblog%2Fusing-mdx.mdx", __ASTRO_IMAGE_IMPORT_ZQqsOE], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fdecibellion.mdx", __ASTRO_IMAGE_IMPORT_Zk9013], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Flisten-harder-audio.mdx", __ASTRO_IMAGE_IMPORT_Z2ndESg], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fshowcase%2Fworld-wide-stereo-storefront.mdx", __ASTRO_IMAGE_IMPORT_iIEJQ]]);
		